ktor:
    deployment:
        port: 8080
    application:
        modules:
            - ru.tbank.ApplicationKt.module
app:
    message: "Hello Tbank"

integration:
    dog-fact:
        host: "https://dogapi.dog/api/v2/"
    cat-fact:
        host: "https://catfact.ninja/"
